version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "80"
    deploy:
      replicas: 3
      
  redis:
    image: redis

